### ISSUE TITLE
GET /offerfilter and required regexp

### ISSUE THREAD

**Issue by nlbi21** [syscoin/syscoin-api#7] opened 2017-04-11 19:17 UTC
Hi guys, I'm trying to get a list of 10 offers with /offerfilter but the optional "regexp" tells me it can not be empty. But in the documentation says it may be empty to bring all offers.

![offers](https://cloud.githubusercontent.com/assets/18112657/24926545/fb82464c-1ec9-11e7-982c-7cd8969cdc97.jpg)

Thanks for the prompt response.

EDIT: Forget it, it's fine guys sorry. Although after the query I get

`"Error: JSON value is not a string as expected"`

with `http://localhost:8001/offerfilter?regexp&from=8&category&safesearch`

**Comment by dwasyluk** [comment] 2017-04-12 00:59
That issue- `"Error: JSON value is not a string as expected"` is something I've fixed in a bunch of places over the past days. I know the root cause, will be fixed as part of 1.0.1.

**Comment by dwasyluk** [comment] 2017-04-17 23:20
@nlbi21 `regexp` is actually required here, when the documentation says "empty" it means an empty string- if you omit `regexp` entirely the server ends up with `null` which is why this is complaining. However, in investigating this I did discover that failure to include and of the other optional params would result in a similar issue, this is now fixed as of the 1.0.1 release. 👍

**Closed by dwasyluk** 2017-04-17 23:20 UTC
Labels: bug
